export const logCabinsDate = [
    {
      id: 1,
      name: "Amelie",
      img1: "Amelie1.png",
      img2: "Amelie2.png",
      img3: "Amelie3.png",
    },
    {
      id: 2,
      name: "Nicole",
      img1: "Nicole1.png",
      img2: "Nicole2.png",
      img3: "Nicole3.png",
    },
    {
      id: 3,
      name: "Matilda",
      img1: "Matilda1.png",
      img2: "Matilda2.png",
      img3: "Matilda3.png",
    },
    {
      id: 4,
      name: "Stella",
      img1: "Stella1.png",
      img2: "Stella2.png",
      img3: "Stella3.png",
    },
    {
      id: 5,
      name: "Victoria",
      img1: "Victoria1.png",
      img2: "Victoria2.png",
      img3: "Victoria3.png",
    },
    {
      id: 6,
      name: "Lolita",
      img1: "Lolita1.png",
      img2: "Lolita2.png",
      img3: "Lolita3.png",
    },
    {
      id: 7,
      name: "Maria",
      img1: "Maria1.png",
      img2: "Maria2.png",
      img3: "Maria3.png",
    },
    {
      id: 8,
      name: "Hanna",
      img1: "Hanna1.png",
      img2: "Hanna2.png",
      img3: "Hanna3.png",
    },
    {
      id: 9,
      name: "Ariana",
      img1: "Ariana1.png",
      img2: "Ariana2.png",
      img3: "Ariana3.png",
    },
    {
      id: 10,
      name: "Nora",
      img1: "Nora1.png",
      img2: "Nora2.png",
      img3: "Nora3.png",
    },
    {
      id: 11,
      name: "Kilkenny",
      img1: "Kilenny1.png",
      img2: "Kilenny2.png",
      img3: "Kilenny3.png",
    },
    {
      id: 12,
      name: "Veronica",
      img1: "Veronica1.png",
      img2: "Veronica2.png",
      img3: "Veronica3.png",
    },
    {
      id: 13,
      name: "Adele Two Room",
      img1: "AdeleTwoRoom1.png",
      img2: "AdeleTwoRoom2.png",
      img3: "AdeleTwoRoom3.png",
    },
    {
      id: 14,
      name: "Bbq house",
      img1: "BbqHouse1.png",
      img2: "BbqHouse2.png",
      img3: "BbqHouse3.png",
    },
    {
      id: 15,
      name: 'Budget one bed B',
      img1: 'BudgetOneBedB1.png',
      img2: 'BudgetOneBedB2.png',
      img3: 'BudgetOneBedB3.png',
    },
    {
      id: 16,
      name: 'Budget two bed D',
      img1: 'BudgetTwoBedD1.png',
      img2: 'BudgetTwoBedD2.png',
      img3: 'BudgetTwoBedD3.png',
    },
    {
      id: 17,
      name: 'Budget two bed A',
      img1: 'BudgetTwoBedA1.png',
      img2: 'BudgetTwoBedA2.png',
      img3: 'BudgetTwoBedA3.png',
    },
    {
      id: 18,
      name: 'Budget two bed C',
      img1: 'BudgetTwoBedC1.png',
      img2: 'BudgetTwoBedC2.png',
      img3: 'BudgetTwoBedC3.png',
    },
    {
      id: 19,
      name: 'Budget Three bed A',
      img1: 'BudgetThreeBedA1.png',
      img2: 'BudgetThreeBedA2.png',
      img3: 'BudgetThreeBedA3.png',
    },
    {
      id: 20,
      name: 'Budget Three bed B',
      img1: 'BudgetThreeBedB1.png',
      img2: 'BudgetThreeBedB2.png',
      img3: 'BudgetThreeBedB3.png',
    },
    {
      id: 21,
      name: 'Budget Four bed A',
      img1: 'BudgetFourBedA1.png',
      img2: 'BudgetFourBedA2.png',
      img3: 'BudgetFourBedA3.png',
    },
    {
      id: 22,
      name: 'Budget Four bed B',
      img1: 'BudgetFourBedB1.png',
      img2: 'BudgetFourBedB2.png',
      img3: 'BudgetFourBedB3.png',
    },
    {
      id: 23,
      name: 'Dublin studio',
      img1: 'DublinStudio1.png',
      img2: 'DublinStudio2.png',
      img3: 'DublinStudio3.png',
    },
    {
      id: 24,
      name: 'One Bed C',
      img1: 'OneBedC1.png',
      img2: 'OneBedC2.png',
      img3: 'OneBedC3.png',
    },
    {
      id: 25,
      name: 'One Bed E',
      img1: 'OneBedE1.png',
      img2: 'OneBedE2.png',
      img3: 'OneBedE3.png',
    },
    {
      id: 26,
      name: 'One Bed D',
      img1: 'OneBedD1.png',
      img2: 'OneBedD2.png',
      img3: 'OneBedD3.png',
    },
    {
      id: 27,
      name: 'Loft log cabin A',
      img1: 'LoftLogCabinA1.png',
      img2: 'LoftLogCabinA2.png',
      img3: 'LoftLogCabinA3.png',
    },
    {
      id: 28,
      name: 'Two bed D',
      img1: 'TwoBedD1.png',
      img2: 'TwoBedD2.png',
      img3: 'TwoBedD3.png',
    },
    {
      id: 29,
      name: 'Two bed E',
      img1: 'TwoBedE1.png',
      img2: 'TwoBedE2.png',
      img3: 'TwoBedE3.png',
    },
    {
      id: 30,
      name: 'Two bed C',
      img1: 'TwoBedC1.png',
      img2: 'TwoBedC2.png',
      img3: 'TwoBedC3.png',
    },
    {
      id: 31,
      name: 'Two bed F',
      img1: 'TwoBedF1.png',
      img2: 'TwoBedF2.png',
      img3: 'TwoBedF3.png',
    },
    {
      id: 32,
      name: 'Three bed A',
      img1: 'ThreeBedA1.png',
      img2: 'ThreeBedA2.png',
      img3: 'ThreeBedA3.png',
    },
    {
      id: 33,
      name: 'Three bed B',
      img1: 'ThreeBedB1.png',
      img2: 'ThreeBedB2.png',
      img3: 'ThreeBedB3.png',
    },
    {
      id: 34,
      name: 'Four bed A',
      img1: 'FourBedA1.png',
      img2: 'FourBedA2.png',
      img3: 'FourBedA3.png',
    },
];
