export const residential = [
	{
		id: 15,
		name: "Budget one bed B",
		img1: "BudgetOneBedB1.png",
		img2: "BudgetOneBedB2.png",
		img3: "BudgetOneBedB3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 1,
		size: '6m x 5.2m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 16,
		name: "Budget two bed D",
		img1: "BudgetTwoBedD1.png",
		img2: "BudgetTwoBedD2.png",
		img3: "BudgetTwoBedD3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 2,
		size: '9.2m x 5.2m ',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 17,
		name: "Budget two bed A",
		img1: "BudgetTwoBedA1.png",
		img2: "BudgetTwoBedA2.png",
		img3: "BudgetTwoBedA3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 2,
		size: '5.2m x 8.2m + 2.0m veranda',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 18,
		name: "Budget two bed C",
		img1: "BudgetTwoBedC1.png",
		img2: "BudgetTwoBedC2.png",
		img3: "BudgetTwoBedC3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 2,
		size: '10m x 7m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 19,
		name: "Budget Three bed A",
		img1: "BudgetThreeBedA1.png",
		img2: "BudgetThreeBedA2.png",
		img3: "BudgetThreeBedA3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 3,
		size: '10.2m x 7m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 20,
		name: "Budget Three bed B",
		img1: "BudgetThreeBedB1.png",
		img2: "BudgetThreeBedB2.png",
		img3: "BudgetThreeBedB3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 3,
		size: '7m x 12.5m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 21,
		name: "Budget Four bed A",
		img1: "BudgetFourBedA1.png",
		img2: "BudgetFourBedA2.png",
		img3: "BudgetFourBedA3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 4,
		size: '8m x 14m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 22,
		name: "Budget Four bed B",
		img1: "BudgetFourBedB1.png",
		img2: "BudgetFourBedB2.png",
		img3: "BudgetFourBedB3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 4,
		size: '9m x 15.5m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 24,
		name: "One Bed C",
		img1: "OneBedC1.png",
		img2: "OneBedC2.png",
		img3: "OneBedC3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 1,
		size: '5.8m x 5m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 25,
		name: "One Bed E",
		img1: "OneBedE1.png",
		img2: "OneBedE2.png",
		img3: "OneBedE3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 1,
		size: '5.0m x 5.8m + 1.5m veranda',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 26,
		name: "One Bed D",
		img1: "OneBedD1.png",
		img2: "OneBedD2.png",
		img3: "OneBedD3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 1,
		size: '5.8m x 5m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 27,
		name: "Loft log cabin A",
		img1: "LoftLogCabinA1.png",
		img2: "LoftLogCabinA2.png",
		img3: "LoftLogCabinA3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 1,
		size: '4.5m x 6m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 28,
		name: "Two bed D",
		img1: "TwoBedD1.png",
		img2: "TwoBedD2.png",
		img3: "TwoBedD3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 2,
		size: '6m x 6m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 29,
		name: "Two bed E",
		img1: "TwoBedE1.png",
		img2: "TwoBedE2.png",
		img3: "TwoBedE3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 2,
		size: '6m x 7.5m',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 30,
		name: "Two bed C",
		img1: "TwoBedC1.png",
		img2: "TwoBedC2.png",
		img3: "TwoBedC3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 2,
		size: '6m x 8m + 1.5m veranda',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 31,
		name: "Two bed F",
		img1: "TwoBedF1.png",
		img2: "TwoBedF2.png",
		img3: "TwoBedF3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 2,
		size: '6m x 9.5m + 1.5m veranda',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 32,
		name: "Three bed A",
		img1: "ThreeBedA1.png",
		img2: "ThreeBedA2.png",
		img3: "ThreeBedA3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		bedrooms: 3,
		size: '7m x 11m + 1.5m veranda',
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 33,
		name: "Three bed B",
		img1: "ThreeBedB1.png",
		img2: "ThreeBedB2.png",
		img3: "ThreeBedB3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		size: '6m x 11m',
		bedrooms: 3,
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	},
	{
		id: 34,
		name: "Four bed A",
		img1: "FourBedA1.png",
		img2: "FourBedA2.png",
		img3: "FourBedA3.png",
		wall_sickness: '44mm/ 70mm/ 90mm',
		size: '8m x 12m + 1.5m veranda',
		bedrooms: 4,
		doors:"Single glazed wooden doors/ double glazed wooden doors/ double glazed PVC doors/ premium living type wooden doors",
		windows: 'Single glazed wooden windows/ double glazed wooden windows/ double glazed PVC windows/ premium living type tilt-and-turn wooden windows',
		roof: 'Steel roof tiles/ Shingle roof tiles',
		floor_bearers: '45mm x 100mm/ 50x150mm',
		floor_roof_boards: "19mm/30mm",
	}
];
